package com.fastsync.database;

/**
 * Result of a lock acquisition attempt.
 *
 * <p>When the lock is acquired, a <strong>fencing token</strong> is returned.
 * This token is a monotonically increasing number generated by the database
 * (via {@code fencing_token = fencing_token + 1} on each successful lock).
 *
 * <p>Per Martin Kleppmann's analysis of distributed locking, the fencing token
 * is the critical defence against stale writes caused by GC pauses, network
 * delays, or clock skew. Even if a server believes it holds the lock, its write
 * will be rejected by the storage layer if a newer fencing token has already
 * been issued:
 * <pre>
 *   Server A acquires lock → fencing token 33 → GC pause → lease expires
 *   Server B acquires lock → fencing token 34 → writes to DB (token 34)
 *   Server A resumes       → writes to DB (token 33) → REJECTED (33 < 34)
 * </pre>
 *
 * @param acquired     whether the lock was successfully acquired
 * @param fencingToken the fencing token assigned to this lock holder (0 if not acquired)
 */
public record LockResult(boolean acquired, long fencingToken) {

    /** Sentinel for a failed lock acquisition. */
    public static final LockResult FAILED = new LockResult(false, 0);

    /**
     * Create a successful lock result with the given fencing token.
     */
    public static LockResult success(long fencingToken) {
        return new LockResult(true, fencingToken);
    }
}
